graph LR
  module_src_features_map_view_adapters_findMapMarker_test_ts["src/features/map-view/adapters/findMapMarker.test.ts"]
  module_src_features_map_view_adapters_findMapMarker_ts["src/features/map-view/adapters/findMapMarker.ts"]
  module_src_features_map_view_adapters_MapView_native_tsx["src/features/map-view/adapters/MapView.native.tsx"]
  module_src_features_map_view_adapters_MapView_web_tsx["src/features/map-view/adapters/MapView.web.tsx"]
  module_src_features_map_view_adapters_toExpoCameraPosition_test_ts["src/features/map-view/adapters/toExpoCameraPosition.test.ts"]
  module_src_features_map_view_adapters_toExpoCameraPosition_ts["src/features/map-view/adapters/toExpoCameraPosition.ts"]
  module_src_features_map_view_adapters_toMapLibreViewState_test_ts["src/features/map-view/adapters/toMapLibreViewState.test.ts"]
  module_src_features_map_view_adapters_toMapLibreViewState_ts["src/features/map-view/adapters/toMapLibreViewState.ts"]
  module_src_features_map_view_defineMapsAdapter_ts["src/features/map-view/defineMapsAdapter.ts"]
  module_src_features_map_view_MapView_ts["src/features/map-view/MapView.ts"]
  module_src_index_native_ts["src/index.native.ts"]
  module_src_index_test_ts["src/index.test.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_index_web_ts["src/index.web.ts"]
  module_src_types_maps_ts["src/types/maps.ts"]
  export_defineMapsAdapter["defineMapsAdapter"]
  module_src_features_map_view_defineMapsAdapter_ts --> export_defineMapsAdapter
  export_defineMapsAdapter -.-> export_MapsAdapter
  export_MapCamera["MapCamera"]
  module_src_types_maps_ts --> export_MapCamera
  export_MapCamera -.-> export_MapCoordinate
  export_MapCameraChangeEvent["MapCameraChangeEvent"]
  module_src_types_maps_ts --> export_MapCameraChangeEvent
  export_MapCameraChangeEvent -.-> export_MapCamera
  export_MapCoordinate["MapCoordinate"]
  module_src_types_maps_ts --> export_MapCoordinate
  export_MapDimension["MapDimension"]
  module_src_types_maps_ts --> export_MapDimension
  export_MapMarker["MapMarker"]
  module_src_types_maps_ts --> export_MapMarker
  export_MapMarker -.-> export_MapCoordinate
  export_MapMarkerPressEvent["MapMarkerPressEvent"]
  module_src_types_maps_ts --> export_MapMarkerPressEvent
  export_MapMarkerPressEvent -.-> export_MapMarker
  export_MapsAdapter["MapsAdapter"]
  module_src_types_maps_ts --> export_MapsAdapter
  export_MapsAdapter -.-> export_MapsPlatform
  export_MapsAdapter -.-> export_MapViewComponent
  export_MapsPlatform["MapsPlatform"]
  module_src_types_maps_ts --> export_MapsPlatform
  export_MapView["MapView"]
  module_src_features_map_view_MapView_ts --> export_MapView
  export_MapView -.-> export_MapViewProps
  export_MapViewComponent["MapViewComponent"]
  module_src_types_maps_ts --> export_MapViewComponent
  export_MapViewProps["MapViewProps"]
  module_src_types_maps_ts --> export_MapViewProps
  export_MapViewProps -.-> export_MapCamera
  export_MapViewProps -.-> export_MapCameraChangeEvent
  export_MapViewProps -.-> export_MapMarker
  export_MapViewProps -.-> export_MapMarkerPressEvent
  export_MapViewProps -.-> export_MapViewStyle
  export_MapViewProps -.-> export_MapWebConfiguration
  export_MapViewStyle["MapViewStyle"]
  module_src_types_maps_ts --> export_MapViewStyle
  export_MapViewStyle -.-> export_MapDimension
  export_MapWebConfiguration["MapWebConfiguration"]
  module_src_types_maps_ts --> export_MapWebConfiguration
